/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enterprisebusinessintelligence.view.business;

import enterprisebusinessintelligence.controllerdao.ConnectionPool;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author Nanan Tanoh
 */
public class ProductionRegionForm extends javax.swing.JDialog {
public static int idP=1;
    /**
     * Creates new form ProductionRegion
     * @param parent
     * @param modal
     * @param chartTitle
     */
    public ProductionRegionForm(java.awt.Frame parent, boolean modal,String chartTitle) {
        super(parent, modal);
        initComponents();
      // This will create the dataset 
        PieDataset dataset = createDataset();
        // based on the dataset we create the chart
        JFreeChart chart = createChart(dataset, chartTitle);
        // we put the chart into a panel
        ChartPanel chartPanel = new ChartPanel(chart);
        // default size
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
        // add it to our application
        setContentPane(chartPanel);
    }
 /**
     * Creates a sample dataset
     */
    private PieDataset createDataset() {
        DefaultPieDataset result = new DefaultPieDataset();
        
        try {
            String sql_stmt = "SELECT  PRODUCTIONS.idPRODUCTS,SUM(productions.quantityProduction) as sum, PRODUCTS.namePRODUCTS,REGIONS.nameREGIONS FROM productions,PRODUCTS,COUNTRIES,REGIONS WHERE PRODUCTIONS.idPRODUCTS = "+idP +" AND PRODUCTIONS.idPRODUCTS=PRODUCTS.idPRODUCTS"+" AND PRODUCTIONS.idCOUNTRIES=COUNTRIES.idCOUNTRIES"+" AND PRODUCTIONS.regionsID=REGIONS.idREGIONS GROUP BY regionsID";
                   
            Statement st = ConnectionPool.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql_stmt);
            while (rs.next()) {
                result.setValue(rs.getInt("sum")+" units "+rs.getString("REGIONS.nameREGIONS"), rs.getInt("sum"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(ProductionCountryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return result;
    }

    /**
     * Creates a chart
     */
    private JFreeChart createChart(PieDataset dataset, String title) {

        JFreeChart chart = ChartFactory.createPieChart3D(title, // chart title
                dataset, // data
                true, // include legend
                true,
                false);

        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        return chart;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(808, 473));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
